# Numpy Array and Basics 

In [1]:
import numpy as np

Creating Array From List 

In [2]:
arr_1d = np.array([1,2,3,4,5])
print("1D Array : ",arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D Array : ",arr_2d) 

1D Array :  [1 2 3 4 5]
2D Array :  [[1 2 3]
 [4 5 6]]


## List vs Numpy array

In [4]:
py_list = [1,2,3,4,5]
print("Python List Multiplication : ",py_list *2)

np_arr = np.array([1,2,3,4,5])
print("Numpy Array Multiplication : ",np_arr *2)

import time
start = time.time()
py_list = [i*2 for i in range (1000000)]
print("\n List Multiplication Time : ",time.time() - start)

start = time.time()
np = np.arange(1000000)*2
print("\n Numpy Array Multiplication Time : ",time.time() - start)

Python List Multiplication :  [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Numpy Array Multiplication :  [ 2  4  6  8 10]

 List Multiplication Time :  0.06984424591064453

 Numpy Array Multiplication Time :  0.007328987121582031


# Creating Array From  Scratch 

In [5]:
import numpy as np

zeros = np.zeros((3, 4))
print("zeros Array \n : ", zeros)

ones = np.ones((3, 4))
print("ones Array \n : ", ones)

Full = np.full((3, 4), 5)
print("Full Array \n : ", Full)

random = np.random.random((2,7))
print("random Array \n : ", random)

sequence = np.arange(0, 10, 2)
print("sequence Array \n : ", sequence)

zeros Array 
 :  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones Array 
 :  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Full Array 
 :  [[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
random Array 
 :  [[0.54226425 0.77930667 0.38942643 0.22544038 0.6703099  0.15017476
  0.42051599]
 [0.96897572 0.63642937 0.67236536 0.74014053 0.19317972 0.19758958
  0.48890442]]
sequence Array 
 :  [0 2 4 6 8]


# Vector , Matrix and Tensor 

In [2]:
import numpy as np

vector = np.array ([1,2,3,4,5])
print ("Vector :", vector)

matrix = np.array ([[1,2,3],
                    [4,5,6]])
print ("Matrix :\n", matrix)
print ("Matrix Shape : ", matrix.shape)
print ("Matrix Size : ", matrix.size)
print ("Matrix Dimension : ", matrix.ndim)
print ("Matrix Data Type : ", matrix.dtype)


Vector : [1 2 3 4 5]
Matrix :
 [[1 2 3]
 [4 5 6]]
Matrix Shape :  (2, 3)
Matrix Size :  6
Matrix Dimension :  2
Matrix Data Type :  int64


# Array Reshaping 

In [5]:
arr = np.arange(12)
print("Original Array \n : ", arr )

reshaped = arr.reshape((3,4))
print("Reshaped Array \n : ", reshaped) 

flatten = reshaped.flatten()
print("Flatten Array \n : ", flatten)

raveled = reshaped.ravel()
print("Raveled Array \n : ", raveled)

transpose = reshaped.T
print("Transpose Array \n : ", transpose)

Original Array 
 :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array 
 :  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flatten Array 
 :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled Array 
 :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose Array 
 :  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
