Numpy Array Operation 

In [1]:
import numpy as np

In [3]:
arr = np.arange(12)
print("Basic Slicing : ", arr[2:5])
print("Step Slicing : ", arr[2:8:2])

Basic Slicing :  [2 3 4]
Step Slicing :  [2 4 6]


In [6]:
arr_2d = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

print("specific element : ", arr_2d[1,2])
print("Row Slicing : ", arr_2d[1])

specific element :  6
Row Slicing :  [4 5 6]


SORTING 

In [7]:
unsorted  = np.array([3,1,2,4,5,6,7,8,9])
print("Unsorted Array : ", unsorted)
print("Sorted Array : ", np.sort(unsorted))

Unsorted Array :  [3 1 2 4 5 6 7 8 9]
Sorted Array :  [1 2 3 4 5 6 7 8 9]


Unsorted Array In 2D 


In [15]:
arr_2d = np.array([[3,1], [1,2],[2,3]])

print("Original Array : ", arr_2d)
print ("Sorted 2D Array by column : ", np.sort(arr_2d, axis = 1))

Original Array :  [[3 1]
 [1 2]
 [2 3]]
Sorted 2D Array by column :  [[1 3]
 [1 2]
 [2 3]]


Filtering 

In [16]:
numbers = np.array([3,1,2,4,5,6,7,8,9])
even = numbers[numbers % 2 == 0]
print("Original Array : ", numbers)
print("Filtered Array : ", even)

Original Array :  [3 1 2 4 5 6 7 8 9]
Filtered Array :  [2 4 6 8]


Filter and Mask 

In [17]:
mask =  numbers > 5
print ("Numbers Greater than 5 : ", numbers[mask])

Numbers Greater than 5 :  [6 7 8 9]


### Fasning Indexing 

In [25]:
indices = [0, 2, 4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print("NP where result : ",numbers[where_result])

[3 2 5]
NP where result :  [6 7 8 9]


In [29]:
conditions_array = np.where(numbers>5 , "True", "False")
print(conditions_array)

['False' 'False' 'False' 'False' 'False' 'True' 'True' 'True' 'True']


Add or Removing Data 

In [31]:
arr1  = np.array([1,2,3])
arr2  = np.array([4,5,6])

combined = np.concatenate((arr1, arr2))  
print(combined)

[1 2 3 4 5 6]


# Array compatibility

In [33]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

print("Compatible shapes : ", a.shape == b.shape == c.shape)

Compatible shapes :  True


In [36]:
original = np.array([[1,2,], [3,4]])
new_row = np.array([5,6])

with_new_row = np.vstack((original, new_row))
print(with_new_row)
print(original)

new_column = np.array([[7], [8]])

with_new_column = np.hstack((original, new_column))
print("with_new_column : ", with_new_column)

[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]]
with_new_column :  [[1 2 7]
 [3 4 8]]


In [38]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr, 2)
print("Array after deletion : ", deleted)

Array after deletion :  [1 2 4 5]
