In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
array_1 = np.array([[1,2,3,],[4,5,6]])
array_2 = np.random.rand(3,3)
array_3 = np.zeros((3,3))


In [3]:
np.save('array_1.npy',array_1)
np.save('array_2.npy',array_2)
np.save('array_3.npy',array_3)

In [4]:
loaded_array_1 = np.load('array_1.npy')
loaded_array_2 = np.load('array_2.npy')
loaded_array_3 = np.load('array_3.npy')

print(loaded_array_1)
print(loaded_array_2)
print(loaded_array_3)

[[1 2 3]
 [4 5 6]]
[[0.68277182 0.97333471 0.31910497]
 [0.49083229 0.30825933 0.31360001]
 [0.0406893  0.6011535  0.627274  ]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
try:
    logo = np.load('numpy-logo.npy')

    # Display
    plt.figure(figsize=(10, 5))
    plt.subplot(121)
    plt.imshow(logo)
    plt.title("Numpy logo")
    plt.grid('off')

except FileNotFoundError:
    print("numpy logo file not found")


numpy logo file not found
